### ISSUE TITLE
Wireframes Missing Submission!

### ISSUE THREAD

**Issue by minhkhang1795** [Syoda/Syoda#2]
It looks like you guys have not created wireframes for your app. Please create the wireframes that show all of the screens and the flow of the app. 

Please call me in this issue once you update your work :smile:
Best.

**Comment by phil-kt** [comment]
@vuminhkhang1995 sorry, spring break. wireframes are up.

**Comment by minhkhang1795** [comment]
:+1: Wow, your wireframes are amazing! Wireframing is a common practice when building apps as it lets you create a blueprint for the app before writing any code. Having a really good blueprint that you can refer to throughout the rest of the project is a really valuable resource and will make it much easier to split up work across your team. It would be better if you did demonstrate how your screens interact with one another, but your current wireframes did show that you guys clearly understand the flow of your app.

With the wireframes in hand, you should have a good idea of what your app will look like when you finish the project. Next week we'll jump into the data schema.
